# Generated by Django 4.1.2 on 2022-11-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
