# Generated by Django 4.1.2 on 2022-11-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=255, upload_to=''),
        ),
    ]
