# Generated by Django 4.1.2 on 2022-11-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_product_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(related_name='stocks', through='logistic.StockProduct', to='logistic.product', verbose_name='Продукт'),
        ),
        migrations.AlterUniqueTogether(
            name='stockproduct',
            unique_together={('stock', 'product')},
        ),
    ]
